[build]
builder = "NIXPACKS"
buildCommand = """
apt-get update && \
apt-get install -y curl apt-transport-https gnupg unixodbc unixodbc-dev && \
mkdir -p /etc/apt/keyrings && \
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg && \
echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main' > /etc/apt/sources.list.d/mssql-release.list && \
apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 && \
cp /opt/microsoft/msodbcsql18/lib64/libodbc.so.2 /usr/lib/x86_64-linux-gnu/ && \
pip install -r requirements.txt
"""

[start]
startCommand = "gunicorn app:app"
